Main/urls.py
import re
from django.urls import path, re_path
from django.conf import settings

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.indexView, name='index'),
    path('upload', views.UploadView.as_view(), name='upload'),
    path('modifie', views.ModifieView.as_view(), name='modifie'),
    path('delete', views.deleteVideo, name='delete'),
    path('watch', views.watchView, name='watch'),
    path('search', views.searchView, name='search'),
    path('playlist', views.PlaylistView.as_view(), name='playlist'),
    path('playlist/<str:id>/delete', views.deletePlaylistView, name='delete_playlist'),
    path('api/impression', views.submitImpressionView.as_view(), name='impressions'),
    path('api/playlists', views.ApiPlaylists.as_view(), name='playlists_api'),
    path('api/subscribe', views.SubscribeView.as_view(), name='subscribe'),
    path('api/submitview', views.submitViews, name='submit_view'),
    path('api/comment', views.ApiComments.as_view(), name='comments_api'),
    path('api/channel', views.ChannelApiView.as_view(), name='channel_api'),
]

if settings.DEBUG :
    urlpatterns += [
        re_path(r'^%s(?P<path>.*)$' % re.escape(settings.MEDIA_URL.lstrip('/')), views.staticView, name='media')
    ]

channel/urls.py
from django.urls import path

from . import views

app_name = 'channel'

urlpatterns = [
    path('<str:id>/', views.index, name='index'),
    path('<str:id>/modifie', views.ModifieChannel.as_view(), name='modifie'),
    path('<str:id>/videos', views.videosView, name='videos'),
    path('<str:id>/playlists', views.playlistsView, name='playlists'),
    path('<str:id>/about', views.aboutChannel, name='about'),
    path('<str:id>/subscriptions', views.subscriptionsChannel, name='subscriptions'),
]

youtube_clone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static, serve

from accounts.urls import urlpatterns as authUrlPatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Main.urls')),
    path('channel/', include('channel.urls')),
] + authUrlPatterns

Main/models.py
from django.db import models
from django.contrib.auth.models import User

from uuid import uuid4
from datetime import timedelta

from .utils import *

class ContentType(models.Model) :
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)

    class Meta :
        constraints = [
            models.UniqueConstraint(fields=['name',], name='unique_content_name')        
        ]

class Video(models.Model) :
    id = models.TextField(primary_key=True, max_length=11, default=generateId, editable=False)
    channel = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=1500, blank=True, null=True)
    duration = models.IntegerField(default=0)
    content_type = models.ForeignKey(ContentType, null=True, on_delete=models.SET_NULL, blank=True)
    allow_comments = models.BooleanField(default=True)
    views = models.IntegerField(default=0)
    # Dates 
    posted_date = models.DateTimeField(auto_now_add=True, editable=False)
    updated_date = models.DateTimeField(auto_now=True)
    # Media
    video_url = models.CharField(max_length=500)
    thumbnail_url = models.CharField(max_length=500)

    class Meta :
        constraints = [
            models.UniqueConstraint(fields=['channel', 'title'], name='unique_videos_per_channel'),
            models.UniqueConstraint(fields=['video_url'], name='unique_videos_url'),
            models.UniqueConstraint(fields=['thumbnail_url'], name='unique_thumbnail_url'),
        ]

    def add_view(self) :
        self.views = self.views + 1 
        self.save()

    def get_duration(self) :
        return str(timedelta(seconds=self.duration))

class Playlist(models.Model) :
    id = models.TextField(primary_key=True, max_length=35, default=generetePlaylistId, editable=False)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=1500, blank=True, null=True)
    is_public = models.BooleanField(default=True)
    videos = models.ManyToManyField(Video)
    views = models.IntegerField(default=0)
    # Dates 
    created_date = models.DateTimeField(auto_now_add=True, editable=False)
    updated_date = models.DateTimeField(auto_now=True)    

    class Meta :
        constraints = [
            models.UniqueConstraint(fields=['creator', 'title'], name='unique_playlist_per_user')
        ]

    def add_view(self) :
        self.views = self.views + 1  

class Comment(models.Model) :
    id = models.UUIDField(primary_key=True, default=uuid4)
    content = models.TextField(max_length=1500)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    # Dates 
    created_date = models.DateTimeField(auto_now_add=True, editable=False)
    updated_date = models.DateTimeField(auto_now=True) 

class VideoImpression(models.Model) :
    class Kind(models.IntegerChoices) :
        LIKE = 1
        DISLIKE = -1

    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    kind = models.IntegerField(choices=Kind.choices, default=1)

    class Meta :
        constraints = [
            models.UniqueConstraint(fields=['video', 'user'], name='one_impression_foreach_user_on_a_video')
        ]

class Subscription(models.Model) :
    channel = models.ForeignKey(User, on_delete=models.CASCADE, related_name='users')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='channels')
    notify = models.BooleanField(default=False)

    class Meta :
        constraints = [
            models.UniqueConstraint(fields=['channel', 'user'], name='unique_subscription')
        ]

Main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseForbidden, HttpResponse, Http404, JsonResponse
from django.views import View
from django.conf.urls.static import serve
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.urls import reverse
from django.middleware.csrf import get_token
from django.db import utils
from django.db.models import Q, QuerySet
from django.contrib import messages

import os, json, random
from datetime import datetime, timedelta
from uuid import uuid4

from .utils import *
from .models import *
from channel.models import *

def indexView(request) :
    total_views = 0
    average_views = 0

    for video in Video.objects.all() : total_views += video.views 
    if total_views > 0 and Video.objects.count() > 0 : average_views = total_views / Video.objects.count()
    
    latest_videos_ids = [video.id for video in 
    Video.objects.filter(views__gte=average_views).filter(posted_date__date__gte=datetime.now() - timedelta(days=7)).order_by('-posted_date')[:30]]

    random.shuffle(latest_videos_ids)
    latest_videos_ids = latest_videos_ids[:10]
    random.shuffle(latest_videos_ids)

    if len(latest_videos_ids) < 10 :
        for v in Video.objects.all().order_by('-views', '-posted_date') :
            if v.id not in latest_videos_ids :
                latest_videos_ids.append(v.id)
            if len(latest_videos_ids) >= 10 :
                break

    if request.user.is_authenticated :
        channels = [subs.channel for subs in request.user.channels.all()]
        for ch in channels :
            ch_videos = ch.video_set.filter(posted_date__date__gte=datetime.now() - timedelta(days=7))
            for vd in ch_videos :
                if vd.id not in latest_videos_ids : latest_videos_ids.append(vd.id)

    random.shuffle(latest_videos_ids)
    latest_videos_ids = latest_videos_ids[:20]
    random.shuffle(latest_videos_ids)
    
    latests = QuerySet(Video).filter(id__in=latest_videos_ids)
    
    context = {
        'videos': latests
    }

    return render(request, 'main/index.html', context)

def watchView(request) :
    try :
        id = request.GET.get('v')
        pl_id = request.GET.get('list')
        video = Video.objects.get(pk=id)
        likes = video.videoimpression_set.filter(kind=1).count()
        dislikes = video.videoimpression_set.filter(kind=-1).count()
        comments = video.comment_set.all().order_by('-created_date')
        related = getRelatedVideos(video)
        user_impr = None
        subscribed = False
        playlist = None
        get_token(request)
    except Video.DoesNotExist :
        raise Http404

    if pl_id is not None :
        try :
            pl = Playlist.objects.get(pk=pl_id)
            
            if video not in pl.videos.all() :
                return redirect(reverse('main:watch') + f'?v={id}')

            if pl.is_public or pl.creator == request.user :
                playlist = pl
            else :
                return redirect(reverse('main:watch') + f'?v={id}')
        except Playlist.DoesNotExist :
            return redirect(reverse('main:watch') + f'?v={id}')

    if request.user.is_authenticated :
        try :
            user = request.user
            user_impr = VideoImpression.objects.get(user=user, video=video)
            user_impr = user_impr.kind
            subscribed = user in [subs.user for subs in video.channel.users.all()]
        except VideoImpression.DoesNotExist :
            user_impr = None

    context = {
        'video': video, 
        'likes': likes, 
        'dislikes': dislikes, 
        'user_impr': user_impr, 
        'subscribed': subscribed, 
        'comments': comments,
        'related': related,
        'playlist': playlist
    }

    return render(request, 'main/watch.html', context)

class submitImpressionView(View) :
    def post(self, request) :
        if not request.user.is_authenticated :
            return redirect(reverse('login'))
        else:
            try :
                body = json.loads(request.body)
                id = body.get('id')
                kind = int(body.get('kind'))
                video = Video.objects.get(pk=id)
                user = request.user
                impression, created = VideoImpression.objects.get_or_create(user=user, video=video)
                impression.kind = kind
                impression.save()

                return HttpResponse(status=201)
            except Video.DoesNotExist:
                raise Http404

    def delete(self, request) :
        if not request.user.is_authenticated :
            return HttpResponseForbidden()
        else:
            try :
                body = json.loads(request.body)
                id = body.get('id')
                video = Video.objects.get(pk=id)
                user = request.user
                impression = VideoImpression.objects.get(user=user, video=video)
                impression.delete()
                
                return HttpResponse(status=202)
            except Video.DoesNotExist or VideoImpression.DoesNotExist :
                raise Http404

class ApiPlaylists(View) :
    def get(self, request) :
        if not request.user.is_authenticated :
            return redirect(reverse('login'))
        else :
            user = request.user
            playlists = user.playlist_set.all()
            playlists = [{'id': pl.id, 'title': pl.title, 'is_public': pl.is_public, 'items': [v.id for v in pl.videos.all()]} for pl in playlists]
            body = {'playlists': playlists}
            return HttpResponse(json.dumps(body))

    def put(self, request) :
        user = request.user
        try :
            body = json.loads(request.body)
            videoId = body.get('videoId')
            playlistId = body.get('playlistId')
            action = int(body.get('action'))
            video = Video.objects.get(pk=videoId)
            playlist = Playlist.objects.get(pk=playlistId)
        except Playlist.DoesNotExist or Video.DoesNotExist :
            raise Http404

        if playlist.creator == user :
            if action == 1 : playlist.videos.add(video)
            if action == -1 : playlist.videos.remove(video)
            return HttpResponse(status=201)
        else :
            return HttpResponseForbidden()

    def post(self, request) :
        user = request.user
        if not user.is_authenticated :
            return HttpResponseForbidden()
        else :
            try :
                body = json.loads(request.body)
                video = Video.objects.get(pk=body.get('videoId'))
                playlist = Playlist(title=body.get('title'), creator=user)
                if body.get('privacy') : playlist.is_public = False
                playlist.save()
                playlist.videos.add(video)
                playlist.save()
                return HttpResponse(json.dumps({'id': playlist.id}), status=201)
            except Video.DoesNotExist :
                return HttpResponse('Video Does Not Exist.', status=400)
            except utils.IntegrityError :
                return HttpResponse('Playlist name already exists.', status=400)

class ModifieView(View) :
    def get(self, request) :
        try :
            id = request.GET.get('v')
            video = Video.objects.get(pk=id)
        except Video.DoesNotExist :
            raise Http404
        
        if video.channel == request.user :
            types = ContentType.objects.all()
            return render(request, 'main/modifie.html', {'video': video, 'types': types})
        else :
            return redirect(reverse('main:watch') + f'?v={video.id}')

    def post(self, request) :
        try :
            id = request.POST.get('id')
            video = Video.objects.get(pk=id)
        except Video.DoesNotExist :
            raise Http404

        if video.channel == request.user :
            # Get Post data
            title = request.POST.get('title')
            description = request.POST.get('description')
            content_type_id = int(request.POST.get('content_type'))
            allow_comments = True
            poster_file = request.FILES.get('poster')

            if request.POST.get('comments') == 'on' :
                allow_comments = False

            if poster_file is not None :
                fn, ext = os.path.splitext(poster_file.name)
                poster_name = f'images/thumbnails/{generateId(30)}{ext}'
                fs = FileSystemStorage()
                poster = fs.save(poster_name, poster_file)
                poster_url = fs.url(poster)
                video.thumbnail_url = poster_url

            video.title = title
            video.allow_comments = allow_comments
            if content_type_id > 0 : video.content_type = ContentType.objects.get(pk=content_type_id)
            if description != '' : video.description = description
            try :
                video.save()
            except utils.IntegrityError :
                messages.error(request, 'Each video in your channel should have a unique title')
            except Exception as ex:
                messages.error(request, ex)

            return redirect(reverse('main:modifie') + f'?v={video.id}')
        else :
            return HttpResponseForbidden()
        
def deleteVideo(request) :
    video_id = request.GET.get('v') or request.POST.get('v')
    video = Video.objects.get(pk=video_id)
    if video.channel == request.user :
        video.delete() 
        return redirect(reverse('main:index'))
    else :
        return HttpResponseForbidden()

class UploadView(View) :
    def get(self, request) :
        if request.user.is_authenticated :
            return render(request, 'main/upload.html')
        else :
            messages.info(request, 'The page you requested is members only.')
            return redirect(reverse('login') + f'?next={request.path}')

    def post(self, request) :

Main/templates/main/index.html
{% extends 'main/main_base.html' %}

{% load humanize %}
{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block content %}
<div class="videos-container">
    {% for video in videos %}
    <div class="video">
        <a data-duration="{{ video.get_duration }}" class="poster" href="{% url 'main:watch' %}?v={{ video.id }}">
            <img src="{{ video.thumbnail_url }}">
        </a>
        <div class="info">
            <a class="channel_profil" href="{% url 'channel:index' video.channel.channel.id %}">
                <img src="{{ video.channel.channel.profil_img }}" />
            </a>

            <div class="right">
                <a href="{% url 'main:watch' %}?v={{ video.id }}" class="title">{{ video.title }}</a>
                <a href="{% url 'channel:index' video.channel.channel.id %}" class="channel">{{ video.channel.channel.title }}</a>
                <p class="details">{{ video.views|intword }} view{{ video.views|pluralize }} • {{ video.posted_date|naturaltime }}</p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

{% block script %}{% endblock %}

Main/templates/main/main_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %} <title>youtube Clone</title> {% endblock %}

    <!-- Font awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css" integrity="sha384-REHJTs1r2ErKBuJB0fCK99gCYsVjwxHrSU0N7I1zl9vZbggVJXRMsv/sLlOAGb4M" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/switch.css' %}">

    {% block styles %}{% endblock %}
</head>
<body>
    <header>
        <button class="nav_bars" id="nav_bars">
            <i class="fas fa-bars"></i>
        </button>

        <div class="logo_div">
            <a href="{% url 'main:index' %}">
                <h1>YoutubeClone</h1>
            </a>
        </div>

        <form action="{% url 'main:search' %}" class="search_form">
            <input name="query" type="text" {% if query %}value='{{query}}'{% endif %} placeholder="Search" />
            <button>
                <i class="fa fa-search" aria-hidden="true"></i>
            </button>
        </form>

        <div class="utils-div">
            <a href="{% url 'main:upload' %}">Upload</a>
        {% if request.user.is_authenticated %}
            <a href="{% url 'logout' %}?next={{request.get_full_path}}" class="btn">logout</a>
        {% else %}
        
            <a href="{% url 'login' %}?next={{request.get_full_path}}" class="btn">Sign In</a>
        
        {% endif %}

            <label class="switch" id="theme_switch">
                <input type="checkbox" />
                <span class="slider round"></span>
            </label>
        </div>

        <div class="backboard" id="backboard"></div>
        <nav class="nav" id="nav">
            <div class="nav_header">
                <button id="hide_nav">
                    <i class="fas fa-times"></i>
                </button>
                
            </div>
            <ul>
                <li><a href="{% url 'main:index' %}">Home</a></li>
                <li><a href="{% url 'user' %}">Channel</a></li>
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'channel:subscriptions' request.user.channel.id %}">Abonnements</a></li>
                <li><a href="{% url 'channel:videos' request.user.channel.id %}">Vos videos</a></li>
                <li><a href="{% url 'channel:playlists' request.user.channel.id %}">Playlists</a></li>
                {% else %}
                <li><a href="{% url 'user' %}">Abonnements</a></li>
                <li><a href="{% url 'user' %}">Vos videos</a></li>
                <li><a href="{% url 'user' %}">Playlists</a></li>
                {% endif %}
            </ul>
            <ul class="playlists" id="nav_bar_playlists"></ul>
        </nav>
    </header>

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <div class="auth-blackboard" id="auth-blackboard"></div>
    <div class="auth-display" id="auth-display">
        <button id="close-auth">
            <i class="fas fa-times"></i>
        </button>
        <a href="{% url 'login' %}?next={{ request.get_full_path }}">Sign in</a>
        <a href="{% url 'register' %}?next={{ request.get_full_path }}">New account</a>
    </div>

    <script src="{% static 'js/theme.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    
    {% block script %}{% endblock %}
</body>
</html>

Main/templates/main/modifie.html
{% extends 'main/main_base.html' %}

{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/modifie.css' %}">
{% endblock %}

{% block content %}
<div class="modifie-lab">
    <div class="poster-container">
        <img id="video-poster" src="{{ video.thumbnail_url }}" alt="video-poster" />
        <label for="video-poster-input">Change Poster</label>
    </div>

    <form class="modifie-form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" value="{{ video.id }}" name="id">
        <input type="file" id="video-poster-input" name="poster" accept="image/*">
        <div class="form-group">
            <label for="video-title">Title :</label>
            <input id="video-title" class="video-title" name="title" type="text" value="{{video.title}}" required />
        </div>

        <div class="form-group">
            <label for="video-description">Description :</label>
            <textarea class="video-description" id="video-description" name="description" maxlength="1500"
            >{% if video.description %}{{ video.description }}{%endif%}</textarea>
        </div>

        <div class="form-group">
            <label for="video-content_type">Content Type :</label>
            <select id="video-content_type" class="video-content_type" name="content_type" selected="{% if video.content_type %}{{ video.content_type.id }}{% else %}0{% endif %}">
                <option value="0"{% if not video.content_type %}selected{% endif %}>Choose Content Type...</option>
                {% for type in types %}
                <option value="{{ type.id }}" {% if video.content_type.id == type.id %}selected{% endif %} >{{ type.name }}</option>
                {% endfor %}
            </select>
        </div>
        
        <div class="form-group check-group">
            <label for="video-disable_comments">Disable Comments :</label>
            <input id="video-disable_comments" class="video-disable_comments" type="checkbox" name="comments"
            {% if not video.allow_comments %}checked{% endif %} />

            <small>Disabling comments will delete all previous comments immediately</small>
        </div>

        {% if messages %}
        {% for msg in messages%}
        <div class="message message-{{msg.tags}}">
            <p>{{ msg }}</p>
        </div>
        {% endfor %}
        {% endif %}

        <button><i class="fas fa-cloud-upload-alt"></i>Save</button>
    </form>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'js/modifie.js' %}"></script>
{% endblock %}

Main/templates/main/playlist.html
{% extends 'main/main_base.html' %}

{% load static %}
{% load humanize %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/playlist.css' %}"/>
{% endblock %}

{% block content %}
<div class="playlist-container">
    <div class="playlist-info">
        <div class="poster">
            <img src="{% if playlist.videos.all.count > 0 %}
            {{ playlist.videos.first.thumbnail_url }}{% else %}
            /media/images/thumbnails/default.jpeg        
            {% endif %}">
            <a class="watch" href="{% url 'main:watch' %}?v={{playlist.videos.first.id}}&list={{playlist.id}}">watch</a>
        </div>

        <div class="title" id="playlist-title">
            <h6>{{ playlist.title }}</h6>
            {% if playlist.creator == request.user %}
            <button data-id="{{ playlist.id }}" id="edit-title" >
                <i class="fas fa-pen"></i>
            </button>
            {% endif %}
        </div>

        <p class="channel">Created by <a href="{% url 'channel:index' playlist.creator.channel.id %}">{{playlist.creator.channel.title }}</a></p>
        <p class="items-count">{{ playlist.videos.all.count }} video{{ playlist.videos.count|pluralize }}</p>
        
        {% if playlist.creator == request.user %}
        <div class="privacy-div">
            <label>private :</label>
            <input data-id="{{ playlist.id }}" id="privacy-input" type="checkbox" {% if not playlist.is_public %}checked{% endif %} />
        </div>
        <a href="{% url 'main:delete_playlist' playlist.id  %} " class="delete">delete</a>
        {% endif %}
    </div>
    <div class="playlist-items">
        {% for video in playlist.videos.all %}
        <div class="video" id="{{ video.id }}">
            <a data-duration="{{video.get_duration}}" class="poster" href="{% url 'main:watch' %}?v={{video.id}}&list={{playlist.id}}">
                <img src="{{ video.thumbnail_url }}" />
            </a>

            <div class="info">
                <a class="title" href="{% url 'main:watch' %}?v={{video.id}}&list={{playlist.id}}">{{ video.title }} </a>
                <a class="channel" href="{% url 'channel:index' video.channel.channel.id %}">{{ video.channel.channel.title }} </a>
            </div>
            
            <div class="holder">
                {% if playlist.creator == request.user %}
                <button class="remove-video" data-id="{{ video.id }}" data-playlist="{{ playlist.id }}">
                    <i class="fas fa-trash"></i>
                </button>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}



{% block script %}
<script src="{% static 'js/playlist.js' %}"></script>
{% endblock %}

Main/templates/main/search.html
{% extends 'main/main_base.html' %}

{% load static %}
{% load humanize %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/search.css' %}" >
{% endblock %}

{% block content %}
<div class="search-container">
    {% if videos_results|length > 0 %}
    <div class="videos">
    {% for video in videos_results %}
        <div class="video">
            <a data-duration="{{ video.get_duration }}" class="poster" href="{% url 'main:watch' %}?v={{video.id}}">
                <img src="{{ video.thumbnail_url }}">
            </a>
            <div class="info">
                <a class="title" href="{% url 'main:watch' %}?v={{video.id}}">{{video.title}}</a>
                <p class="bottom"><a class="channel" href="{% url 'channel:index' video.channel.channel.id %}" >{{video.channel.channel.title}}</a>
                <span>{{ video.views|intword }} view{{ video.views|pluralize }} • {{ video.posted_date|naturaltime }}</span>
                </p>
            </div>
        </div>
    {% endfor %}
    </div>
    {% else %}
    <div class="message message-error" style="text-align: center;margin: 0 auto;">
        <p style="font-weight: 900;font-size: 1.7rem; text-transform: capitalize;">No result found</p>
        <br/>
        <p>Try other keywords or remove the search filters </p>
    </div>
    {% endif %}

    {% if channels_results|length > 0 %}
    <div class="channels">
    <div class="header">
        <h6>Channels :</h6>
    </div>
    {% for channel in channels_results %}
        <div class="channel">
            <a class="poster" href="{% url 'channel:index' channel.id %}">
                <img src="{{ channel.profil_img }}">
            </a>
            <div class="info">
                <a class="title" href="{% url 'channel:index' channel.id %}">{{channel.title}}</a>
                <p class="bottom">{{ channel.user.users.count }} subscriber{{ channel.user.users.count|pluralize }} • {{ channel.user.video_set.count }} video{{ channel.user.video_set.count|pluralize }}
                </p>
            </div>
        </div>
    {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock %}

{% block script %}{% endblock %}