Main/urls.py
import re
from django.urls import path, re_path
from django.conf import settings

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.indexView, name='index'),
    path('upload', views.UploadView.as_view(), name='upload'),
    path('modifie', views.ModifieView.as_view(), name='modifie'),
    path('delete', views.deleteVideo, name='delete'),
    path('watch', views.watchView, name='watch'),
    path('search', views.searchView, name='search'),
    path('playlist', views.PlaylistView.as_view(), name='playlist'),
    path('playlist/<str:id>/delete', views.deletePlaylistView, name='delete_playlist'),
    path('api/impression', views.submitImpressionView.as_view(), name='impressions'),
    path('api/playlists', views.ApiPlaylists.as_view(), name='playlists_api'),
    path('api/subscribe', views.SubscribeView.as_view(), name='subscribe'),
    path('api/submitview', views.submitViews, name='submit_view'),
    path('api/comment', views.ApiComments.as_view(), name='comments_api'),
    path('api/channel', views.ChannelApiView.as_view(), name='channel_api'),
]

if settings.DEBUG :
    urlpatterns += [
        re_path(r'^%s(?P<path>.*)$' % re.escape(settings.MEDIA_URL.lstrip('/')), views.staticView, name='media')
    ]

channel/urls.py
from django.urls import path

from . import views

app_name = 'channel'

urlpatterns = [
    path('<str:id>/', views.index, name='index'),
    path('<str:id>/modifie', views.ModifieChannel.as_view(), name='modifie'),
    path('<str:id>/videos', views.videosView, name='videos'),
    path('<str:id>/playlists', views.playlistsView, name='playlists'),
    path('<str:id>/about', views.aboutChannel, name='about'),
    path('<str:id>/subscriptions', views.subscriptionsChannel, name='subscriptions'),
]

youtube_clone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static, serve

from accounts.urls import urlpatterns as authUrlPatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Main.urls')),
    path('channel/', include('channel.urls')),
] + authUrlPatterns

channel/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.files.uploadedfile import InMemoryUploadedFile

from PIL import Image
from io import BytesIO

from Main.utils import *
from Main.models import *

class Channel(models.Model) :
    id = models.TextField(primary_key=True, max_length=24, default=generateChannelId)
    title = models.CharField(max_length=200)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    about = models.TextField(max_length=1500, null=True, blank=True)
    profil_img = models.TextField(default='/media/images/users/default.png')
    profil_background = models.TextField(default='/media/images/users/default_background.jpeg')
    favorite_video = models.OneToOneField(Video, on_delete=models.SET_NULL, null=True, blank=True, related_name='favorite_video')

    def save(self, *args, **kwargs) :
        if (self.favorite_video is not None) and (self.favorite_video.channel.channel.id != self.id) :
            raise Exception('Favorite video of a channel must be from it.')
        else :
            super(Channel, self).save(*args, **kwargs)

channel/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import Http404, HttpResponseForbidden
from django.views.generic import View
from django.core.files.images import ImageFile
from django.core.files.storage import FileSystemStorage

from datetime import timedelta, time, datetime

from .models import *
from Main.utils import *

def index(request, id) :
    try :
        channel = Channel.objects.get(pk=id)
        subs = channel.user.users.all().count()
        is_subscribed = request.user in [sub.user for sub in channel.user.users.all()]
        videos = channel.user.video_set.all().order_by('-posted_date')[:4]

        for video in videos :
            t = timedelta(seconds=video.duration)
            video.duration = str(t)

        if channel.favorite_video is not None :
            f_video = channel.favorite_video
        elif channel.user.video_set.count() < 1 :
            f_video = None
        else :
            av_views = 0
            total = channel.user.video_set.count()
            for v in channel.user.video_set.all() : av_views += v.views
            av_views = av_views / total
            f_video = channel.user.video_set.filter(views__gt=av_views).order_by('-posted_date')[0]

        context = {
            'channel': channel, 
            'subs': subs, 
            'is_subscribed': is_subscribed, 
            'videos': videos, 
            'channel_index_classes': 'active',
            'f_video': f_video 
        }
        return render(request, 'channel/index.html', context)
    except Channel.DoesNotExist :
        raise Http404

class ModifieChannel(View):
    def get(self, request, id) :
        try :
            channel = Channel.objects.get(pk=id)
        except :
            raise Http404

        if request.user == channel.user :
            return render(request, 'channel/modifie.html', {'channel': channel})
        else :
            return redirect(reverse('channel:index', args=(channel.id,)))

    def post(self, request, id) :
        try :
            channel = Channel.objects.get(pk=id)
        except :
            raise Http404
        
        if request.user == channel.user :
            title = request.POST.get('title')
            about = request.POST.get('about')

            if request.FILES.get('profil-img') is not None :
                fn, ext = os.path.splitext(request.FILES.get('profil-img').name)
                fs = FileSystemStorage()
                profilImg_name = f'images/users/{generateId(30)}{ext}'
                profilImg = fs.save(profilImg_name, request.FILES.get('profil-img'))
                channel.profil_img = fs.url(profilImg)

            if request.FILES.get('background-img') is not None :
                fn, ext = os.path.splitext(request.FILES.get('background-img').name)
                fs = FileSystemStorage()
                backgroundImg_name = f'images/users/{generateId(30)}{ext}'
                backgroundImg = fs.save(backgroundImg_name, request.FILES.get('background-img'))
                channel.profil_background = fs.url(backgroundImg)

            channel.title = title
            channel.about = about
            channel.save()
            return redirect(reverse('channel:modifie', args=(channel.id,)))
        else :
            return HttpResponseForbidden()

def videosView(request, id) :
    try :
        channel = Channel.objects.get(pk=id)
        order = int(request.GET.get('order', 0))
        subs = channel.user.users.all().count()
        is_subscribed = request.user in [sub.user for sub in channel.user.users.all()]
        videos = channel.user.video_set.all()

        if order == 0 :
            videos = videos.order_by('-posted_date')
        elif order == 1 :
            videos = videos.order_by('posted_date')
        elif order == 2:
            videos = videos.order_by('-views')
        else :
            videos = videos.order_by('-posted_date')

        for video in videos :
            t = timedelta(seconds=video.duration)
            video.duration = str(t)

        context = {
            'channel': channel, 
            'subs': subs, 
            'is_subscribed': is_subscribed, 
            'videos': videos,
            'channel_videos_classes': 'active'
        }

        return render(request, 'channel/videos.html', context)
    except Channel.DoesNotExist :
        raise Http404

def playlistsView(request, id) :
    try :
        channel = Channel.objects.get(pk=id)
        subs = channel.user.users.all().count()
        is_subscribed = request.user in [sub.user for sub in channel.user.users.all()]

        if channel.user == request.user :
            playlists = channel.user.playlist_set.all 
        else :
            playlists = channel.user.playlist_set.filter(is_public=True) 

        context = {
            'channel': channel, 
            'subs': subs, 
            'is_subscribed': is_subscribed,
            'channel_playlists_classes': 'active',
            'playlists': playlists
        }

        return render(request, 'channel/playlists.html', context)
    except Channel.DoesNotExist :
        raise Http404

def aboutChannel(request, id) :
    try :
        channel = Channel.objects.get(pk=id)
        subs = channel.user.users.all().count()
        is_subscribed = request.user in [sub.user for sub in channel.user.users.all()]
        views = 0
        for v in channel.user.video_set.all() : views += v.views  

        context = {
            'channel': channel, 
            'subs': subs, 
            'is_subscribed': is_subscribed,
            'channel_about_classes': 'active',
            'views' : views
        }

        return render(request, 'channel/about.html', context)
    except Channel.DoesNotExist :
        raise Http404

def subscriptionsChannel(request, id) :
    try :
        channel = Channel.objects.get(pk=id)

        if channel.user == request.user :
            subs = [c.channel.channel for c in channel.user.channels.all()]

            context = {
                'user_channel': channel,
                'subs_channels': subs
            }
            return render(request, 'channel/subs.html', context)
        else :
            raise Http404
    except Channel.DoesNotExist :
        raise Http404

channel/templates/channel/about.html
{% extends 'channel/main_base.html' %}

{% load static %}

{% block styles_channel %}
<link rel="stylesheet" href="{% static 'css/about_channel.css' %}">
{% endblock %}

{% block content_channel %}
<div class="about-container">
    <div class="description">
        <h6>Description</h6>
        <p class="text-block">{{ channel.about }}</p>
        <hr>
    </div>
    <div class="statistics">
        <h6>Statistics</h6>
        <hr>
        <p>Active sence {{ channel.user.date_joined|date:'d b. Y' }}</p>
        <hr>
        <p>{{ views }} view{{ views|pluralize }} </p>
        <hr>
    </div>
</div>
{% endblock%}

channel/templates/channel/index.html
{% extends 'channel/main_base.html' %}

{% load static %}
{% load humanize %}

{% block styles_channel %}
<link rel="stylesheet" href="{% static 'css/index_channel.css' %}" />
<link rel="stylesheet" href="{% static 'css/video-player.css' %}" />
{% endblock %}

{% block content_channel %}
{% if f_video %}
<div class="favorite_container">
    <div class="video_container" id="video-container">
        <video data-id="{{ f_video.id }}" src="{{ f_video.video_url }}" id="video" preload="metadata"
            poster="{{ f_video.thumbnail_url }}"></video>

        <div class="video_controls" id="video_controls">
            <div class="video-progress">
                <progress id="progress-bar" class="progress-bar" value="0" min="0"></progress>
                <input type="range" class="seek" id="seek" value="0" min="0" step="1">
                <div class="seek-tooltip" id="seek-tooltip">00:00</div>
            </div>

            <div class="bottom-controls">
                <div class="left-controls">
                    <button data-title="Play (k)" id="play">
                        <svg class="">
                            <use href="#play-icon"></use>
                            <use class="hidden" href="#pause"></use>
                        </svg>
                    </button>

                    <div class="volume-controls">
                        <button data-title="Mute (m)" class="volume-button" id="volume-button">
                            <svg>
                                <use class="hidden" href="#volume-mute"></use>
                                <use class="hidden" href="#volume-low"></use>
                                <use href="#volume-high"></use>
                            </svg>
                        </button>

                        <input class="volume" id="volume" value="1" data-mute="0.5" type="range" max="1" min="0"
                            step="0.01">
                    </div>

                    <div class="time">
                        <time id="time-ellapse">00:00</time>
                        <span> / </span>
                        <time id="duration">00:00</time>
                    </div>
                </div>

                <div class="right-controls">
                    <button data-title="PIP (p)" class="pip-button" id="pip-button">
                        <svg>
                            <use href="#pip"></use>
                        </svg>
                    </button>
                    <button data-title="Full screen (f)" class="fullscreen-button" id="fullscreen-button">
                        <svg>
                            <use href="#fullscreen"></use>
                            <use href="#fullscreen-exit" class="hidden"></use>
                        </svg>
                    </button>
                </div>

            </div>
        </div>
    </div>

   <div class="info">
       <h6>{{ f_video.title }}</h6>
       <p class="bottom"><span class="views" data-views="{{ v.views }}">{{ f_video.views }}</span>
        view{{ f_video.views|pluralize }} • {{ f_video.posted_date|naturaltime}}</p>

        {% if f_video.description %}
        <p class="text-block description">{{ f_video.description|make_list|slice:'0:150'|join:'' }}...</p>
        {% else %}
        <p class="description"></p>
        {% endif %}
        <a href="{% url 'main:watch' %}?v={{f_video.id}}" class="more_btn">More</a>
   </div>
</div> 
<hr>
{% endif %}

{% if videos.count > 0 %}
<h3 class="section-title">Latest Videos</h3>
<div class="latest-list">
    {% for video in videos %}
    <div class="video">
        <a class="img-a" data-duration="{{ video.duration }}" href="{% url 'main:watch' %}?v={{video.id}}">
            <img src="{{ video.thumbnail_url }}" alt="{{ video.title }}" />
        </a>
        <div class="video-body">
            <a class="title" href="{% url 'main:watch' %}?v={{video.id}}">
                <h6>{{ video.title }}</h6>
            </a>
            <span class="info">{{ video.views|intword }} view{{ video.views|pluralize }} •
                {{ video.posted_date|naturaltime }}</span>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<div class="message">
    <p>No Videos in This channel</p>
    {% if request.user == channel.user %}
    <a href="{% url 'main:upload' %}">upload</a>
    {% endif %}
</div>
{% endif %}

{% if f_video %}
<!-- Video Player icons -->
<svg style="display: none">
    <defs>
        <symbol id="pause" viewBox="0 0 24 24">
            <path d="M14.016 5.016h3.984v13.969h-3.984v-13.969zM6 18.984v-13.969h3.984v13.969h-3.984z"></path>
        </symbol>

        <symbol id="play-icon" viewBox="0 0 24 24">
            <path d="M8.016 5.016l10.969 6.984-10.969 6.984v-13.969z"></path>
        </symbol>

        <symbol id="volume-high" viewBox="0 0 24 24">
            <path
                d="M14.016 3.234q3.047 0.656 5.016 3.117t1.969 5.648-1.969 5.648-5.016 3.117v-2.063q2.203-0.656 3.586-2.484t1.383-4.219-1.383-4.219-3.586-2.484v-2.063zM16.5 12q0 2.813-2.484 4.031v-8.063q1.031 0.516 1.758 1.688t0.727 2.344zM3 9h3.984l5.016-5.016v16.031l-5.016-5.016h-3.984v-6z">
            </path>
        </symbol>

        <symbol id="volume-low" viewBox="0 0 24 24">
            <path
                d="M5.016 9h3.984l5.016-5.016v16.031l-5.016-5.016h-3.984v-6zM18.516 12q0 2.766-2.531 4.031v-8.063q1.031 0.516 1.781 1.711t0.75 2.32z">
            </path>
        </symbol>

        <symbol id="volume-mute" viewBox="0 0 24 24">
            <path
                d="M12 3.984v4.219l-2.109-2.109zM4.266 3l16.734 16.734-1.266 1.266-2.063-2.063q-1.547 1.313-3.656 1.828v-2.063q1.172-0.328 2.25-1.172l-4.266-4.266v6.75l-5.016-5.016h-3.984v-6h4.734l-4.734-4.734zM18.984 12q0-2.391-1.383-4.219t-3.586-2.484v-2.063q3.047 0.656 5.016 3.117t1.969 5.648q0 2.203-1.031 4.172l-1.5-1.547q0.516-1.266 0.516-2.625zM16.5 12q0 0.422-0.047 0.609l-2.438-2.438v-2.203q1.031 0.516 1.758 1.688t0.727 2.344z">
            </path>
        </symbol>

        <symbol id="fullscreen" viewBox="0 0 24 24">
            <path
                d="M14.016 5.016h4.969v4.969h-1.969v-3h-3v-1.969zM17.016 17.016v-3h1.969v4.969h-4.969v-1.969h3zM5.016 9.984v-4.969h4.969v1.969h-3v3h-1.969zM6.984 14.016v3h3v1.969h-4.969v-4.969h1.969z">
            </path>
        </symbol>

        <symbol id="fullscreen-exit" viewBox="0 0 24 24">
            <path
                d="M15.984 8.016h3v1.969h-4.969v-4.969h1.969v3zM14.016 18.984v-4.969h4.969v1.969h-3v3h-1.969zM8.016 8.016v-3h1.969v4.969h-4.969v-1.969h3zM5.016 15.984v-1.969h4.969v4.969h-1.969v-3h-3z">
            </path>
        </symbol>

        <symbol id="pip" viewBox="0 0 24 24">
            <path
                d="M21 19.031v-14.063h-18v14.063h18zM23.016 18.984q0 0.797-0.609 1.406t-1.406 0.609h-18q-0.797 0-1.406-0.609t-0.609-1.406v-14.016q0-0.797 0.609-1.383t1.406-0.586h18q0.797 0 1.406 0.586t0.609 1.383v14.016zM18.984 11.016v6h-7.969v-6h7.969z">
            </path>
        </symbol>
    </defs>
</svg>
{% endif %}
{% endblock%}

{% block scripts_channel %}
<script src="{% static 'js/video-player.js' %}"></script>
{% endblock %}

channel/templates/channel/main_base.html
{% extends 'main/main_base.html' %}

{% load static %}
{% load humanize %}

{% block title %}
    {% block title_channel %}<title>{{channel.title}} - Youtube Clone</title>{% endblock %}
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/channel.css' %}" />
    {% block styles_channel %}{% endblock %}
{% endblock %}

{% block content %}
<div class="channel-header">
    <div class="wallpaper" style="background-image: url('{{channel.profil_background }}');"></div>
    <div class="info">
        <div class="info-left">
            <img src="{{channel.profil_img }}" alt="{{channel.title}}" />
            <div class="">
                <h3>{{channel.title}}</h3>
                <span data-subscriptions="{{subs}}">{{subs|intword}} subscriber{{ subs|pluralize }}</span>
            </div>
        </div>
        {% if request.user != channel.user %}
        <button class="subscribe-button" id="subscribe-button" data-id="{{channel.id}}" {% if is_subscribed %}data-subscribed{% endif %} >
            {% if is_subscribed %}subscribed{% else %}subscribe{% endif %}</button>
        {% else %}
        <a href="{% url 'channel:modifie' channel.id %}" class="edit-btn modifie">modifie</a>
        {% endif %}
    </div>

    <nav class="channel-nav">
        <ul>
            <li>
                <a class="{{ channel_index_classes }}" href="{% url 'channel:index' channel.id %}">Home</a>
            </li>
            <li>
                <a class="{{ channel_videos_classes }}" href="{% url 'channel:videos' channel.id %}">Videos</a>
            </li>
            <li>
                <a href="{% url 'channel:playlists' channel.id %}" class="{{channel_playlists_classes }}" >Playlists</a>
            </li>
            <li>
                <a href="{% url 'channel:about' channel.id %}" class="{{channel_about_classes }}">About</a>
            </li>
        </ul>
    </nav>
</div>

<div class="channel-container">
{% block content_channel %}{% endblock%} 
</div>

{% endblock %}

{% block script %}
    <script src="{% static 'js/channel.js' %}"></script>
    <script src="{% static 'js/subscribe.js' %}"></script>
    {% block scripts_channel %}{% endblock %}
{% endblock %}

channel/templates/channel/modifie.html
{% extends 'main/main_base.html' %}

{% load static %}

{% block title %}
    <title>Edit {{channel.title}} - Youtube Clone</title>
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/edit_channel.css' %}" />
{% endblock %}

{% block content %}
<div class="alert-backboard" id="alert-backboard"></div>
<div class="alert-display" id="alert-display">
    <button id="close-alert">
        <i class="fas fa-times"></i>
    </button>
    <p id="alert-text"></p>
</div>

<div class="channel-header">
    <label for="background-img" id="wallpaper" class="wallpaper" data-default="{{ channel.profil_background }}" style="background-image: url('{{ channel.profil_background }}');">
        <div>
            <i class="fas fa-edit"></i>
        </div>
    </label>

    <div class="info">
        <div class="info-left">
            <label for="profil-img" id="profil" class="profil-img" data-default="{{ channel.profil_img }}" style="background-image: url('{{ channel.profil_img }}');">
                <div>
                    <i class="fas fa-edit"></i>
                </div>
            </label>

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <input class="channel-title" type="text" name="title" value="{{ channel.title }}" maxlength="50" />
                <input class="hidden" type="file" id="profil-img" name="profil-img" accept="image/*" />
                <input class="hidden" type="file" id="background-img" name="background-img" accept="image/*" />
                <textarea name="about" class="hidden" id="about"></textarea>
                <input class="hidden" type="submit" id="submit-form" />
            </form>
        </div>
        <a class="return-btn" href="{% url 'channel:index' channel.id %} ">Home</a>
    </div>
</div>

<div class="about-form">
    <label class="about-label">Describe your channel in few lines :</label>
    <textarea class="about-area" id="about-area" maxlength="1500">{% if channel.about %}{{ channel.about }}{% endif %}</textarea>
    <label for="submit-form" class="submit-btn">Save</label>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'js/edit-channel.js' %}"></script>
{% endblock %}

channel/templates/channel/playlists.html
{% extends 'channel/main_base.html' %}

{% load static %}
{% load humanize %}

{% block styles_channel %}
<link rel="stylesheet" href="{% static 'css/playlists_channel.css' %}">
{% endblock %}

{% block content_channel %}
<div class="playlists-container">
{% for playlist in playlists %}
<div class="playlist">
    <a class="poster" href="{% if playlist.videos.all.count > 0 %}
        {% url 'main:watch' %}?v={{playlist.videos.first.id}}&list={{playlist.id}}
        {% else %}{% url 'main:playlist' %}?id={{playlist.id}}{% endif %}">
        <img src="{% if playlist.videos.all.count > 0 %}
        {{ playlist.videos.first.thumbnail_url }}{% else %}
        /media/images/thumbnails/default.jpeg        
        {% endif %}" alt="{{playlist.title}}">
        <div class="play">
            <i class="fas fa-play"></i>
        </div>
    </a>
    <a class="title" href="{% if playlist.videos.all.count > 0 %}
    {% url 'main:watch' %}?v={{playlist.videos.first.id}}&list={{playlist.id}}
    {% else %}{% url 'main:playlist' %}?id={{playlist.id}}{% endif %}">{{playlist.title}} 
    {% if playlist.videos.all.count > 0 %}
    ({{ playlist.videos.count }} video{{ playlist.videos.count|pluralize }}) {% else %} (Empty) {% endif %}</a>
</div>
{% endfor %} 
</div>
{% endblock%}

channel/templates/channel/subs.html
{% extends 'main/main_base.html' %}

{% load humanize %}
{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/subscriptions.css' %}" />
{% endblock %}

{% block content %}
<div class="channels-container">
    {% for channel in subs_channels %}
    <div class="channel">
        <a class="poster" href="{% url 'channel:index' channel.id %}">
            <img src="{{ channel.profil_img }}">
        </a>
        <a class="title" href="{% url 'channel:index' channel.id %}">{{ channel.title }}</a>
        <p class="views">{{ channel.user.users.count|intword }} subscriber{{ channel.user.users.count|pluralize }}</p>
    </div>
    {% endfor %}
</div>
{% endblock %}

{% block script %}{% endblock %}

channel/templates/channel/videos.html
{% extends 'channel/main_base.html' %}

{% load static %}
{% load humanize %}

{% block styles_channel %}
<link rel="stylesheet" href="{% static 'css/videos.css' %}" />
{% endblock %}

{% block content_channel %}
{% if videos.count > 0 %}
<div class="videos-container-control">
    <div class="dropdown-menu" id="dropdown-menu">
        <button id="order-by">Order By</button>
        <div class="dropdown-list" id="dropdown-list">
            <a href="{{ request.get_absolute_url }}?order=0">Recent Posted</a>
            <a href="{{ request.get_absolute_url }}?order=1">Older Posted</a>
            <a href="{{ request.get_absolute_url }}?order=2">Most Popular</a>
        </div>
    </div>
</div>
<div class="videos-container">
    {% for video in videos %}
    <div class="video">
        {% if request.user == channel.user %}
        <button class="set-favorite{% if channel.favorite_video == video %} favorite{% endif %}" data-id="{{ video.id }}" data-channel="{{ channel.id }}"
        {% if channel.favorite_video == video %}data-fav{% endif %}>
            <i class="fas fa-star filled"></i>
            <i class="far fa-star empty"></i>
        </button>
        {% endif %}
        <a class="img-a" data-duration="{{ video.duration }}" href="{% url 'main:watch' %}?v={{video.id}}">
            <img src="{{ video.thumbnail_url }}" alt="{{ video.title }}" />
        </a>
        <div class="video-body">
            <a class="title" href="{% url 'main:watch' %}?v={{video.id}}">
                <h6>{{ video.title }}</h6>
            </a>
            <span class="info">{{ video.views|intword }} view{{ video.views|pluralize }} •
                {{ video.posted_date|naturaltime }}</span>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<div class="message">
    <p>No Videos in This channel</p>
    {% if request.user == channel.user %}
    <a href="{% url 'main:upload' %}">upload</a>
    {% endif %}
</div>
{% endif %}
{% endblock%}


{% block scripts_channel %}
<script src="{% static 'js/videos_channel.js' %}"></script>
{% endblock %}